clc;
clear all;
N = 1024;
f1 = 1;
Fs = 200;
n = 0 : N - 1;
x = sin(2*pi*f1*n/Fs);
t = [1:N]*(1/Fs);
subplot(2, 1, 1);
plot(t, x);
title('Sinewave of frequency 1Hz[Fs = 200Hz]');
xlabel('time, [s]');
ylabel('Amplitude');
grid;
Rxx = xcorr(x);
subplot(2, 1, 2);
plot(Rxx);
grid;
title('Autocorrelation function of the sinewave');
xlabel('lags');
ylabel('Autocorrelation');
