x = [2 1 2 1];
h = [1 2 3];
clin = conv(x, h);
subplot(3, 1, 1);
stem(x);
title('Input Sequence');
xlabel('n-->');
ylabel('x(n)');
subplot(3, 1, 2);
stem(h);
title('Impulse Sequence');
xlabel('n-->');
ylabel('h(n)');
subplot(3, 1, 3);
stem(clin);
title('linear convolution');
xlabel('n-->');
ylabel('y(n)');
disp(clin);
